"""Tests for the Substrate's LLM-driven code paths.

These stub the async LLMEngine methods with canned parsed responses so the
evaluate/decide/reflect/curiosity/parametric-mod/code-self-mod branches run
deterministically and offline (no provider calls, no real source edits).
"""
import asyncio

from aegis.layers.substrate import Substrate
from aegis.config import LLM_THINK_EVERY_N_TICKS


def _make_substrate():
    s = Substrate()

    async def _noop_agents():
        return []

    async def _noop_learn(*a, **k):
        return {"success": False}

    s.agent_system.run_due_agents = _noop_agents
    s.external_learning.learn_from_source = _noop_learn
    s.environment.step = lambda: {"reward": 0.0, "solved": False, "task": None}
    # LLM is ON, but every provider call is stubbed below.
    s.llm.enabled = True

    async def _eval_state(state):
        return {"success": True, "response": "ok", "parsed": {
            "assessment": "stable", "insight": "energy drives exploration",
            "suggested_goals": ["learn topology", "improve memory"]}}

    async def _make_decision(options, ctx):
        return {"success": True, "response": "ok", "parsed": {
            "chosen": 1, "reasoning": "best expected value", "confidence": 0.8}}

    async def _reflect(ep):
        return {"success": True, "response": "ok", "parsed": {
            "learning": "reflection stabilizes mood",
            "knowledge": {"concept": "homeostasis", "definition": "self-regulation"}}}

    async def _curiosity(known):
        return {"success": True, "response": "ok", "parsed": {
            "topic": "emergent computation", "question": "how does it arise?",
            "connection": "links to complexity"}}

    s.llm.evaluate_state = _eval_state
    s.llm.make_decision = _make_decision
    s.llm.reflect = _reflect
    s.llm.generate_curiosity = _curiosity
    return s


def _llm_tick_number(base: int) -> int:
    """Return a tick_count value such that the NEXT tick() lands on an LLM tick."""
    # tick() increments first, so we want (base+1) % N == 0.
    n = LLM_THINK_EVERY_N_TICKS
    target = ((base // n) + 1) * n
    return target - 1


def test_llm_evaluate_and_decide_and_reflect_run():
    async def run():
        s = _make_substrate()
        s.tick_count = _llm_tick_number(10)
        insight_before = len(s.memory.episodic)
        await s.tick()
        # The evaluate/reflect stubs add episodic insight entries.
        assert len(s.memory.episodic) > insight_before
        # A suggested goal from evaluate_state was appended.
        assert any(g.reasoning == "Generated by LLM evaluation" for g in s.goals.goals)
    asyncio.run(run())


def test_llm_reflection_adds_semantic_concept():
    async def run():
        s = _make_substrate()
        s.tick_count = _llm_tick_number(20)
        await s.tick()
        # reflect() stub returns a knowledge concept -> stored in semantic memory.
        assert "homeostasis" in s.memory.semantic
    asyncio.run(run())


def test_llm_curiosity_exploration_adds_topic():
    async def run():
        s = _make_substrate()
        # Curiosity fires when tick_count % (LLM_THINK_EVERY_N_TICKS*5) == 0.
        s.tick_count = LLM_THINK_EVERY_N_TICKS * 5 - 1
        await s.tick()
        assert "emergent computation" in s.memory.semantic
    asyncio.run(run())


def test_parametric_modification_applies_within_bounds():
    async def run():
        s = _make_substrate()

        async def _analyze(metrics):
            return {"success": True, "parsed": {"adjustments": [
                {"parameter": "curiosity_weight", "direction": "increase",
                 "magnitude": 0.05, "reason": "encourage exploration"}]}}

        s.llm.analyze_self_performance = _analyze
        before = s.self_mod.parameters["curiosity_weight"]
        await s._llm_parametric_modification()
        after = s.self_mod.parameters["curiosity_weight"]
        # Either applied (increased) or safely rejected — never crashes, never
        # leaves an out-of-bounds value.
        lo, hi = s.self_mod._param_bounds["curiosity_weight"]
        assert lo <= after <= hi
        assert after >= before
    asyncio.run(run())


def test_parametric_modification_ignores_unknown_param():
    async def run():
        s = _make_substrate()

        async def _analyze(metrics):
            return {"success": True, "parsed": {"adjustments": [
                {"parameter": "does_not_exist", "direction": "increase",
                 "magnitude": 0.05}]}}

        s.llm.analyze_self_performance = _analyze
        snapshot = dict(s.self_mod.parameters)
        await s._llm_parametric_modification()  # must not raise or change anything
        assert s.self_mod.parameters == snapshot
    asyncio.run(run())


def test_code_self_modification_no_change_path():
    async def run():
        s = _make_substrate()
        # Stub the code modifier so nothing touches the real package source.
        s.code_modifier.list_sources = lambda: [
            {"path": "toy.py", "immutable": False, "size": 100}]
        s.code_modifier.read_source = lambda p: "x = 1\n"

        async def _propose(path, src, state):
            return {"success": True, "parsed": {
                "should_modify": False, "reason": "already optimal"}}

        s.llm.propose_code_change = _propose
        applied = {"n": 0}
        s.code_modifier.apply_modification = lambda *a, **k: applied.__setitem__("n", applied["n"] + 1) or {"status": "applied"}
        await s._code_self_modification()
        assert applied["n"] == 0  # no modification attempted
    asyncio.run(run())


def test_code_self_modification_applies_when_safe(monkeypatch):
    async def run():
        # Code self-modification is opt-in (audit C2); enable it for this path.
        import aegis.layers.substrate as substrate_mod
        monkeypatch.setattr(substrate_mod, "CODE_SELF_MOD_ENABLED", True)
        s = _make_substrate()
        s.code_modifier.list_sources = lambda: [
            {"path": "toy.py", "immutable": False, "size": 100}]
        s.code_modifier.read_source = lambda p: "x = 1\n"

        async def _propose(path, src, state):
            return {"success": True, "parsed": {
                "should_modify": True,
                "modified_code": "x = 2  # improved\n",
                "description": "bump constant"}}

        s.llm.propose_code_change = _propose
        calls = {"applied": 0}

        def _apply(path, code, desc, author="llm"):
            calls["applied"] += 1
            return {"status": "applied_pending_restart"}

        s.code_modifier.apply_modification = _apply
        await s._code_self_modification()
        # Passed ethics + self-preservation (benign change) -> apply was called.
        assert calls["applied"] == 1
        assert s._code_mod_count_session == 1
    asyncio.run(run())
